baseURL: "https://0art0.github.io/lambda-cube"
title: "λ-cube"
theme: PaperMod
publishDir: "docs"

enableInlineShortcodes: true
buildDrafts: true
buildFuture: true
enableEmoji: true
pygmentsUseClasses: true

params:
  description: "A blog on mathematics, foundations, computer science, theorem provers and more."
  author: Anand

  defaultTheme: auto
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true
  comments: true

  params.page:
   twemoji: false
   lightgallery: false
   fontawesome: true
   rssFullText: true

   params.page.toc:
      enable: true
      keepStatic: false
      auto: true

   params.page.math:
      enable: true
      copyTex: true
      mhchem: true

   params.page.code:
      copy: true
      maxShownLines: 25

   params.page.share:
      enable: true

   params.page.comment:
      enable: true

  homeInfoParams:
    Title: "λ-cube"
    Content: >
      Welcome to **λ-cube**, a blog on mathematics, foundations, computer science, theorem provers and more. 

  socialIcons:
    - name: github
      url: "https://github.com/0art0"

    - name: Rss
      url: "index.xml"

  editPost:
    URL: "https://github.com/0art0/lambda-cube/tree/main/content"
    Text: "View source"
    appendFilePath: true
